- name: Check that we can push to the external registry
  ansible.builtin.fail:
    msg: "REGISTRY: '{{ external_registry }}' and REGISTRY_TOKEN: '{{ external_registry_token }}'. Both need to be set"
  failed_when: >
    (external_registry is not defined or external_registry | length == 0) or
    (external_registry_token is not defined or external_registry_token | length == 0)

- name: Get current cluster pull secrets
  ansible.builtin.command:
    oc extract secret/pull-secret -n openshift-config --to=-
  register: pull_secrets_raw

- name: Add external registry to pull secrets and set auth fact
  ansible.builtin.set_fact:
    pull_secrets_new: "{{ pull_secrets_raw.stdout | from_json }}"
    external_registry_auth: "{{ external_registry_token | b64encode }}"

- name: Add local registry to pull secrets
  ansible.builtin.set_fact:
    pull_secrets: "{{ pull_secrets_new | combine({'auths': {external_registry.split('/')[0]: {'email': external_registry_email, 'auth': external_registry_auth}}}, recursive=true) }}"

- name: Get a tempfile for the pull secrets
  ansible.builtin.tempfile:
    state: directory
  register: pull_secrets_tempfolder

- name: Store pull secrets in tempfile
  ansible.builtin.copy:
    dest: "{{ pull_secrets_tempfolder.path }}/.dockerconfigjson"
    content: "{{ pull_secrets | to_nice_json }}"
    mode: "0644"

# We cannot store the logins back in the cluster, because quay.io would be overwritten and not have
# access to the images openshift needs. See:
# https://github.com/moby/moby/issues/37569
# - name: Update pull-secret in the cluster
#   ansible.builtin.shell: |
#     oc set data secret/pull-secret -n openshift-config --from-file="{{ pull_secrets_tempfolder.path }}/.dockerconfigjson"
- name: Set Mirror URL fact for external mirror IIB
  ansible.builtin.set_fact:
    mirror_iib: "{{ external_registry }}"

- name: Set Mirror URL fact for external mirror
  ansible.builtin.set_fact:
    mirror_dest: "{{ external_registry }}"
