apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-oauth-credentials
  labels:
    {{- include "devspaces.labels" . | nindent 4 }}   
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: github-oauth-config
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: che.eclipse.org
          app.kubernetes.io/component: oauth-scm-configuration
        annotations:
          che.eclipse.org/oauth-scm-server: github
          che.eclipse.org/scm-server-endpoint: https://github.com
      data:
        id: "{{ "{{" }} .clientID {{ "}}" }}"
        secret: "{{ "{{" }} .clientSecret {{ "}}" }}"   
  data:
  - secretKey: clientID
    remoteRef:
      key: secret/data/hub/github-devspaces
      #version: provider-key-version
      property: client-id
  - secretKey: clientSecret
    remoteRef:
      key: secret/data/hub/github-devspaces
      #version: provider-key-version
      property: client-secret     
