apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: golang-external-secrets
spec:
  provider:
    vault:
      server: https://vault-vault.{{ .Values.global.hubClusterDomain }}
      path: secret
      # Version of KV backend
      version: v2
{{ if .Values.clusterGroup.isHubCluster }}
      caProvider:
        type: ConfigMap
        name: kube-root-ca.crt
        key: ca.crt
        namespace: golang-external-secrets
{{ else }}
      caProvider:
        type: Secret
        name: hub-ca
        key: hub-kube-root-ca.crt
        namespace: imperative
{{ end }}
      auth:
        kubernetes:
{{ if .Values.clusterGroup.isHubCluster }}
          mountPath: {{ .Values.mountPath }}
          role: {{ .Values.mountRole }}
{{ else }}
          mountPath: {{ $.Values.global.clusterDomain }}
          role: {{ $.Values.global.clusterDomain }}-role
{{ end }}
          secretRef:
            name: golang-external-secrets
            namespace: golang-external-secrets
            key: "token"
