apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-pvc
  namespace: devsecops-ci
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.cloudProvider.storageClass }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
