apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
  name: create-cosign-pubkey
  namespace: openshift-pipelines
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
           '/tmp/cosign.sh'
        name: create-cosign-pubkey
        volumeMounts:
          - mountPath: /tmp/cosign.sh
            name: cosign
            subPath: cosign.sh
      volumes:
        - name: cosign
          configMap:
            name: create-cosign-pubkey
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: cosign-sa
      serviceAccountName: cosign-sa
      terminationGracePeriodSeconds: 60
