{{- if not (eq .Values.enabled "plumbing") }}
{{/* This is always defined as we always unseal the cluster with an imperative job */}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Values.clusterGroup.imperative.clusterRoleName }}
rules:
{{- if $.Values.clusterGroup.imperative.clusterRoleYaml -}}
  {{ toYaml $.Values.clusterGroup.imperative.clusterRoleYaml | nindent 2 }}
{{- else }}
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
{{- end }}
{{- end }}
