global:
  extraValueFiles: []

main:
  git:
    repoURL: https://github.com/pattern-clone/mypattern
    revision: main

  gitops:
    channel: "gitops-1.8"
    operatorSource: redhat-operators

  multiSourceConfig:
    enabled: false

  patternsOperator:
    channel: fast
    source: community-operators

  clusterGroupName: default
