apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  namespace: openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-options: ServerSideApply=true
data:
  artifacts.oci.storage: 'oci'
  artifacts.taskrun.format: tekton
  artifacts.taskrun.storage: tekton
  artifacts.oci.format: simplesigning
  artifacts.oci.signer: cosign
