apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secured-cluster-secret-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: secured-cluster-secret
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: med
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - rhacs-operator
              - stackrox
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: admission-control-tls
                  namespace: stackrox
                apiVersion: v1
                data:
                  admission-control-cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-cert.pem" hub}}` }}'
                  admission-control-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-key.pem" hub}}` }}'
                  ca.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "ca.pem" hub}}` }}'
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: sensor-tls
                  namespace: stackrox
                apiVersion: v1
                data:
                  sensor-cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-cert.pem" hub}}` }}'
                  sensor-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-key.pem" hub}}` }}'
                  ca.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "ca.pem" hub}}` }}'
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: collector-tls
                  namespace: stackrox
                apiVersion: v1
                data:
                  collector-cert.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-cert.pem" hub}}` }}'
                  collector-key.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-key.pem" hub}}` }}'
                  ca.pem: '{{ `{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").data "ca.pem" hub}}` }}'


