# The policy needs to be added to the ACM HUB and then it will be pushed on all clusters
# except the HUB (see placementrule on the bottom)
{{ if .Values.clusterGroup.isHubCluster }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-quayio-registry-secret
  namespace: devsecops-ci
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "7"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quayio-secret-configpolicy
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: image-registry-credentials
                  namespace: devsecops-ci
                  annotations:
                    # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
                    tekton.dev/docker-0: https://{{ .Values.global.imageregistry.hostname }}
                apiVersion: v1
                data:
                  username: '{{ `{{hub fromSecret "devsecops-ci" "image-registry-credentials" "username" hub}}` }}'
                  password: '{{ `{{hub fromSecret "devsecops-ci" "image-registry-credentials" "password" hub}}` }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: quayio-secret-placement-binding
  namespace: devsecops-ci
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
placementRef:
  name: quayio-secret-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-quayio-registry-secret
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: quayio-secret-placement
  namespace: devsecops-ci
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  # This will go to both devel and secured clusters
  clusterSelector:
    # Using matchExpression because I need it in more than one clusterGroup
    matchExpressions:
      - key: clusterGroup
        operator: In
        values:
          - devel
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
{{ end }}
